name: Bug Report
description: Laat weten wat er mis ging
title: "fix: "
labels: ["bug", "triage"]
assignees:
  - moranje
body:
  - type: markdown
    attributes:
      value: |
        Fijn dat je laat weten wat je ondervonden hebt!
  - type: input
    id: contact
    attributes:
      label: Contact gegevens
      description: Hoe kan ik je bereiken om meer informatie te vragen?
      placeholder: vb. email@voorbeeld.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: Wat merkte je?
      description: Het helpt mij als je kunt vertellen wat het verwachte
        resultaat was?
      placeholder: Beschrijf wat je zag om een manier dat ik er een beeld bij
        kan krijgen of het na kan bootsen (nog beter)
      value: /
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: In welke browser gebeurd het?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Anders
