---
name: Nieuwe functie
description: Iets nieuws toevoegen?
title: "feat: "
labels: ["feature"]
assignees:
  - moranje
body:
  - type: input
    id: contact
    attributes:
      label: Contact gegevens
      description: Hoe kan ik je bereiken om meer informatie te vragen?
      placeholder: vb. email@voorbeeld.com
    validations:
      required: false
  - type: textarea
    id: feature
    attributes:
      label: Wat wil je toevoegen en hoe zie je dat voor je?
      description: Beschrijf in genoeg detail hoe het werkt
      placeholder: Ga je gang
    validations:
      required: true
